version: '3.8'

services:
  ec2-control-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - TEST_MODE=false
    volumes:
      - ./data:/app/data
    restart: unless-stopped 