version: '3.8'

services:
  ec2-control-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    restart: unless-stopped 