services:
  ec2-slack-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - TEST_MODE=${TEST_MODE:-false}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: >
      sh -c "
        mkdir -p /app/data &&
        chmod 777 /app/data &&
        gunicorn --bind 0.0.0.0:5000 --workers 2 app:app
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 