apiVersion: v1
kind: Service
metadata:
  name: ec2-slack-bot
  namespace: ec2-slack-bot
  labels:
    app: ec2-slack-bot
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ec2-slack-bot.aops.ninja
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ec2-slack-bot 