apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec2-instance-controls
  labels:
    app: ec2-instance-controls
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ec2-instance-controls
  template:
    metadata:
      labels:
        app: ec2-instance-controls
      annotations:
        # EKS-specific annotations for IAM roles
        eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/ec2-controls-role
    spec:
      serviceAccountName: ec2-controls-sa
      containers:
      - name: ec2-control-app
        image: ec2-instance-controls:latest  # Will be replaced by deployment script
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: ec2-controls-config
              key: AWS_REGION
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ec2-controls-config
              key: LOG_LEVEL
        - name: SCHEDULE_DIR
          valueFrom:
            configMapKeyRef:
              name: ec2-controls-config
              key: SCHEDULE_DIR
        # Slack credentials (optional - only if needed)
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-credentials
              key: slack-bot-token
              optional: true
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: slack-credentials
              key: slack-signing-secret
              optional: true
        volumeMounts:
        - name: schedule-storage
          mountPath: /app/schedules
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      volumes:
      - name: schedule-storage
        persistentVolumeClaim:
          claimName: schedule-pvc
      securityContext:
        fsGroup: 1000 