apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schedule-pvc
  namespace: ec2-controls
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3