apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  aws-access-key-id: <base64-encoded-access-key>
  aws-secret-access-key: <base64-encoded-secret-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-credentials
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  slack-bot-token: <base64-encoded-bot-token>
  slack-signing-secret: <base64-encoded-signing-secret> 