apiVersion: v1
kind: Service
metadata:
  name: ec2-instance-controls
  labels:
    app: ec2-instance-controls
spec:
  selector:
    app: ec2-instance-controls
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP 