apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: oz-eks-cluster
  region: us-west-2
  version: "1.32"
  tags:
    ManagedBy: eksctl

# If `useDefaultPodIdentityAssociations` isn't available, then create the
# permissions directly, preferring wellKnownPolicies if available.
iam:
  podIdentityAssociations:
    - namespace: ec2-slack-bot
      serviceAccountName: ack-ec2-controller
      permissionPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess